// Copyright 2026 Ledo / Subteno.
// License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl).
//
// Regenerates SCSS partials from `design-system.dtcg.json`.
//
//   pnpm run tokens
//
// Outputs (overwrites existing files):
//
//   odoo_design_system/static/src/scss/_tokens.generated.scss
//       → @included from _tokens.scss; carries the Sass maps + :root
//         custom properties consumed by the OWL components.
//
//   dist/brand_variables.scss
//       → ready to copy into the consumer-side branding module (e.g.
//         ledoent/erp `private/ledoweb_branding/static/src/scss/`).
//         The path varies per consumer so we ship the file in `dist/`
//         rather than depending on the consumer's directory layout.
//
// Token source: `odoo_design_system/static/src/tokens/design-system.dtcg.json`.
// Format: W3C DTCG (style-dictionary v5 reads $value / $type / $description
// natively when `usesDtcg: true`).

import StyleDictionary from "style-dictionary";

const HEADER = `// Generated by \`pnpm run tokens\` from
// odoo_design_system/static/src/tokens/design-system.dtcg.json.
//
// DO NOT EDIT BY HAND. Change the JSON and re-run.
`;

// ---------------------------------------------------------------------------
// Format: emit the bucket palette + extension palette as Sass maps, then a
// :root block with the size/shadow/motion CSS custom properties.

// Anchor keys inside `color.ext.*` that are semantic categories rather
// than concrete file extensions. They exist in the DTCG JSON so designers
// can reference `{color.ext.image}` from `jpg/png/gif/...` — but consumer
// markup carries actual extensions (`data-ext="jpg"`), so we omit the
// anchors from the runtime Sass map.
const EXT_ANCHORS = new Set(["image", "media", "doc-family", "sheet", "archive"]);

StyleDictionary.registerFormat({
    name: "scss/ods-tokens",
    format: ({dictionary}) => {
        const flat = dictionary.allTokens;
        const get = (path) => flat.find((t) => t.path.join(".") === path);
        const bucketMap = (() => {
            const lines = [];
            for (let i = 1; i <= 8; i++) {
                const t = get(`color.bucket.${i}`);
                if (!t) continue;
                lines.push(`    ${i}: ${t.$value},`);
            }
            return `$ods-bucket-palette: (\n${lines.join("\n")}\n);`;
        })();

        const extMap = (() => {
            const lines = [];
            for (const t of flat) {
                if (t.path[0] !== "color" || t.path[1] !== "ext") continue;
                const ext = t.path[2];
                if (EXT_ANCHORS.has(ext)) continue;
                lines.push(`    "${ext}": ${t.$value},`);
            }
            return `$ods-extension-accents: (\n${lines.join("\n")}\n);`;
        })();

        const cssVars = (() => {
            // style-dictionary's "scss" transform group flattens DTCG
            // shadow $values into the standard "x y blur spread color"
            // string, so we can write t.$value directly without
            // re-assembling the object.
            const lines = [];
            for (const t of flat) {
                if (t.path[0] === "size" || t.path[0] === "motion") {
                    lines.push(`    --ods-${t.path.slice(1).join("-")}: ${t.$value};`);
                }
            }
            const shadowCard = get("shadow.card");
            const shadowHover = get("shadow.card-hover");
            if (shadowCard) {
                lines.push(`    --ods-card-shadow: ${shadowCard.$value};`);
            }
            if (shadowHover) {
                lines.push(`    --ods-card-shadow-hover: ${shadowHover.$value};`);
            }
            return `:root {\n${lines.join("\n")}\n}`;
        })();

        return [
            HEADER,
            "",
            "// ---------------------------------------------------------------------------",
            "// Sass-level palettes — internal source of truth for the generated",
            "// per-identity selectors emitted by the mixins in _tokens-helpers.scss.",
            "",
            bucketMap,
            "",
            extMap,
            "",
            "// ---------------------------------------------------------------------------",
            "// CSS-side tokens — exposed on :root so any component can read them.",
            "",
            cssVars,
            "",
        ].join("\n");
    },
});

// ---------------------------------------------------------------------------
// Format: emit the brand-color overrides for ledoweb_branding.

StyleDictionary.registerFormat({
    name: "scss/brand-variables",
    format: ({dictionary}) => {
        const get = (path) =>
            dictionary.allTokens.find((t) => t.path.join(".") === path);
        const primary = get("color.brand.primary");
        const secondary = get("color.brand.secondary");
        const navDark = get("color.portal.nav-dark");
        const sidebarLight = get("color.portal.sidebar-light");
        const border = get("color.portal.border");

        return [
            HEADER.replace("`pnpm run tokens`", "`pnpm run tokens` (in odoo-design-system)"),
            "// Drop this file into your branding module's `static/src/scss/` and list",
            "// it in `web._assets_primary_variables` so Bootstrap compiles $primary",
            "// correctly against it.",
            "",
            "// Color resolution chain in Odoo 18/19:",
            "//   $o-enterprise-color → base-1 palette 'o-color-1' → $-main-color",
            "//   → 'primary' → $primary. Overriding $o-enterprise-color here",
            "//   (before primary_variables.scss !default) cascades through the",
            "//   entire system.",
            "",
            primary &&
                `$o-enterprise-color: ${primary.$value};\n$o-community-color: ${primary.$value};\n$o-brand-odoo: ${primary.$value};\n$o-brand-primary: ${primary.$value};`,
            secondary && `\n// Lighter variant for hover states\n$o-brand-lighten: ${secondary.$value};`,
            "",
            "// Portal chrome",
            navDark && `$o-portal-nav-dark: ${navDark.$value};`,
            sidebarLight && `$o-portal-sidebar-light: ${sidebarLight.$value};`,
            border && `$o-portal-border: ${border.$value};`,
            "",
        ]
            .filter(Boolean)
            .join("\n");
    },
});

// ---------------------------------------------------------------------------

export default {
    source: ["odoo_design_system/static/src/tokens/design-system.dtcg.json"],
    // Tell style-dictionary to read DTCG $value/$type fields.
    log: {warnings: "warn", verbosity: "default"},
    platforms: {
        "scss-ods-tokens": {
            transformGroup: "scss",
            buildPath: "odoo_design_system/static/src/scss/",
            files: [
                {
                    destination: "_tokens.generated.scss",
                    format: "scss/ods-tokens",
                },
            ],
        },
        "scss-brand": {
            transformGroup: "scss",
            buildPath: "dist/",
            files: [
                {
                    destination: "brand_variables.scss",
                    format: "scss/brand-variables",
                },
            ],
        },
    },
};
