// Copyright 2026 Ledo / Subteno.
// License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl).
//
// Regenerates SCSS partials from `design-system.dtcg.json`.
//
//   pnpm run tokens
//
// Outputs (overwrites existing files):
//
//   odoo_design_system/static/src/scss/_tokens.generated.scss
//       → @included from _tokens.scss; carries the Sass maps + :root
//         custom properties consumed by the OWL components, plus
//         per-theme [data-theme="..."] override blocks.
//
//   dist/brand_variables.scss
//       → ready to copy into the consumer-side branding module (e.g.
//         ledoent/erp `private/ledoweb_branding/static/src/scss/`).
//
// Token source: `odoo_design_system/static/src/tokens/design-system.dtcg.json`.
// Format: W3C DTCG (style-dictionary v5 reads $value / $type / $description
// natively when `usesDtcg: true`). The JSON is multi-set (Tokens Studio
// shape): top-level keys are token sets (`global`, `theme-light`,
// `theme-dark`, `theme-high-contrast`) plus `$themes` + `$metadata` which
// our custom parser strips before style-dictionary ingests the file.

import StyleDictionary from "style-dictionary";

const HEADER = `// Generated by \`pnpm run tokens\` from
// odoo_design_system/static/src/tokens/design-system.dtcg.json.
//
// DO NOT EDIT BY HAND. Change the JSON and re-run.
`;

// ---------------------------------------------------------------------------
// Parser — strip Tokens Studio metadata keys (`$themes`, `$metadata`) from
// the JSON root. style-dictionary treats every leaf as a candidate token;
// these two are arrays/objects with no `$value`, so leaving them in would
// either warn or be silently ignored. Stripping is cleaner.

StyleDictionary.registerParser({
    name: "json-strip-meta",
    pattern: /\.json$/,
    parser: ({contents}) => {
        const json = JSON.parse(contents);
        delete json.$themes;
        delete json.$metadata;
        return json;
    },
});

// ---------------------------------------------------------------------------
// Helpers shared by both formats.

const EXT_ANCHORS = new Set(["image", "media", "doc-family", "sheet", "archive"]);

function tokensFromSet(allTokens, setName) {
    return allTokens.filter((t) => t.path[0] === setName);
}

// Map a token path (without the set prefix) to a CSS custom property name.
// Returns null if the token is Sass-only (bucket / ext palettes).
function cssVarName(pathAfterSet) {
    const [head, ...rest] = pathAfterSet;
    switch (head) {
        case "color": {
            const [group, ...tail] = rest;
            if (group === "bucket" || group === "ext") return null;
            // Drop the "color." prefix to keep names short:
            //   color.surface.canvas  → --ods-surface-canvas
            //   color.text.primary    → --ods-text-primary
            //   color.state.success-bg→ --ods-state-success-bg
            //   color.brand.primary   → --ods-brand-primary
            //   color.neutral.500     → --ods-neutral-500
            //   color.portal.nav-dark → --ods-portal-nav-dark
            return `--ods-${[group, ...tail].join("-")}`;
        }
        case "size":
            // Legacy back-compat: drop the "size." prefix entirely.
            //   size.card-radius → --ods-card-radius
            return `--ods-${rest.join("-")}`;
        case "spacing":
            return `--ods-spacing-${rest.join("-")}`;
        case "radius":
            return `--ods-radius-${rest.join("-")}`;
        case "elevation":
            return `--ods-elevation-${rest.join("-")}`;
        case "typography": {
            const [sub, ...tail] = rest;
            const prefix = {
                "family": "font-family",
                "size": "font-size",
                "weight": "font-weight",
                "line-height": "line-height",
            }[sub];
            if (!prefix) return null;
            return `--ods-${prefix}-${tail.join("-")}`;
        }
        case "motion": {
            const [sub, ...tail] = rest;
            const prefix = {
                "duration": "duration",
                "easing": "easing",
            }[sub];
            if (!prefix) return null;
            return `--ods-${prefix}-${tail.join("-")}`;
        }
        default:
            return null;
    }
}

function emitVarLines(tokens, indent = "    ") {
    const lines = [];
    for (const t of tokens) {
        const name = cssVarName(t.path.slice(1));
        if (!name) continue;
        lines.push(`${indent}${name}: ${t.$value};`);
    }
    return lines;
}

// ---------------------------------------------------------------------------
// Format: emit the bucket palette + extension palette as Sass maps, then a
// :root block carrying the theme-invariant globals AND the light-theme
// overrides (light is the default), then [data-theme="dark"] and
// [data-theme="high-contrast"] override blocks.

StyleDictionary.registerFormat({
    name: "scss/ods-tokens",
    format: ({dictionary}) => {
        const all = dictionary.allTokens;
        const get = (path) => all.find((t) => t.path.join(".") === path);

        const bucketMap = (() => {
            const lines = [];
            for (let i = 1; i <= 8; i++) {
                const t = get(`global.color.bucket.${i}`);
                if (!t) continue;
                lines.push(`    ${i}: ${t.$value},`);
            }
            return `$ods-bucket-palette: (\n${lines.join("\n")}\n);`;
        })();

        const extMap = (() => {
            const lines = [];
            for (const t of all) {
                if (t.path[0] !== "global") continue;
                if (t.path[1] !== "color" || t.path[2] !== "ext") continue;
                const ext = t.path[3];
                if (EXT_ANCHORS.has(ext)) continue;
                lines.push(`    "${ext}": ${t.$value},`);
            }
            return `$ods-extension-accents: (\n${lines.join("\n")}\n);`;
        })();

        const globalTokens = tokensFromSet(all, "global");
        const lightTokens = tokensFromSet(all, "theme-light");
        const darkTokens = tokensFromSet(all, "theme-dark");
        const hcTokens = tokensFromSet(all, "theme-high-contrast");

        const rootBlock = (() => {
            const lines = [
                ...emitVarLines(globalTokens),
                ...emitVarLines(lightTokens),
                "",
                "    /* Legacy aliases — kept for consumers still referencing the pre-Phase-0 names. */",
                "    --ods-card-shadow: var(--ods-elevation-1);",
                "    --ods-card-shadow-hover: var(--ods-elevation-3);",
                "    --ods-card-lift-duration: var(--ods-duration-base);",
                "    --ods-card-lift-easing: var(--ods-easing-standard);",
            ];
            return `:root,\n[data-theme="light"] {\n${lines.join("\n")}\n}`;
        })();

        const themeBlock = (name, tokens) => {
            const lines = emitVarLines(tokens);
            return `[data-theme="${name}"] {\n${lines.join("\n")}\n}`;
        };

        return [
            HEADER,
            "",
            "// ---------------------------------------------------------------------------",
            "// Sass-level palettes — internal source of truth for the generated",
            "// per-identity selectors emitted by the mixins in _tokens.scss.",
            "// These are theme-invariant.",
            "",
            bucketMap,
            "",
            extMap,
            "",
            "// ---------------------------------------------------------------------------",
            "// CSS custom properties.",
            "//",
            "// `:root` carries the theme-invariant globals (spacing, typography,",
            "// radius, motion, brand color, neutral scale, size aliases) AND the",
            "// light-theme color/elevation overrides — light is the default.",
            "//",
            "// `[data-theme=\"dark\"]` and `[data-theme=\"high-contrast\"]` blocks",
            "// override only the theme-specific tokens. Toggle via",
            "//   document.documentElement.dataset.theme = '<name>'",
            "",
            rootBlock,
            "",
            themeBlock("dark", darkTokens),
            "",
            themeBlock("high-contrast", hcTokens),
            "",
        ].join("\n");
    },
});

// ---------------------------------------------------------------------------
// Format: emit the brand-color overrides for ledoweb_branding.

StyleDictionary.registerFormat({
    name: "scss/brand-variables",
    format: ({dictionary}) => {
        const get = (path) =>
            dictionary.allTokens.find((t) => t.path.join(".") === path);
        const primary = get("global.color.brand.primary");
        const secondary = get("global.color.brand.secondary");
        const navDark = get("global.color.portal.nav-dark");
        const sidebarLight = get("global.color.portal.sidebar-light");
        const border = get("global.color.portal.border");

        return [
            HEADER.replace("`pnpm run tokens`", "`pnpm run tokens` (in odoo-design-system)"),
            "// Drop this file into your branding module's `static/src/scss/` and list",
            "// it in `web._assets_primary_variables` so Bootstrap compiles $primary",
            "// correctly against it.",
            "",
            "// Color resolution chain in Odoo 18/19:",
            "//   $o-enterprise-color → base-1 palette 'o-color-1' → $-main-color",
            "//   → 'primary' → $primary. Overriding $o-enterprise-color here",
            "//   (before primary_variables.scss !default) cascades through the",
            "//   entire system.",
            "",
            primary &&
                `$o-enterprise-color: ${primary.$value};\n$o-community-color: ${primary.$value};\n$o-brand-odoo: ${primary.$value};\n$o-brand-primary: ${primary.$value};`,
            secondary && `\n// Lighter variant for hover states\n$o-brand-lighten: ${secondary.$value};`,
            "",
            "// Portal chrome",
            navDark && `$o-portal-nav-dark: ${navDark.$value};`,
            sidebarLight && `$o-portal-sidebar-light: ${sidebarLight.$value};`,
            border && `$o-portal-border: ${border.$value};`,
            "",
        ]
            .filter(Boolean)
            .join("\n");
    },
});

// ---------------------------------------------------------------------------

export default {
    source: ["odoo_design_system/static/src/tokens/design-system.dtcg.json"],
    parsers: ["json-strip-meta"],
    log: {warnings: "warn", verbosity: "default"},
    platforms: {
        "scss-ods-tokens": {
            transformGroup: "scss",
            buildPath: "odoo_design_system/static/src/scss/",
            files: [
                {
                    destination: "_tokens.generated.scss",
                    format: "scss/ods-tokens",
                },
            ],
        },
        "scss-brand": {
            transformGroup: "scss",
            buildPath: "dist/",
            files: [
                {
                    destination: "brand_variables.scss",
                    format: "scss/brand-variables",
                },
            ],
        },
    },
};
