// Copyright 2026 Ledo / Subteno.
// License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl).
//
// Token-contract tests: invariants that the DTCG source + the generated
// SCSS must hold for every theme set. Run via `pnpm run test`.
//
// These run without an Odoo instance — they only read repo files.

import {test} from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {fileURLToPath} from "node:url";
import {dirname, resolve} from "node:path";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const TOKENS_JSON = resolve(ROOT, "odoo_design_system/static/src/tokens/design-system.dtcg.json");
const TOKENS_SCSS = resolve(ROOT, "odoo_design_system/static/src/scss/_tokens.generated.scss");

const json = JSON.parse(readFileSync(TOKENS_JSON, "utf8"));
const scss = readFileSync(TOKENS_SCSS, "utf8");

const THEME_SETS = ["theme-light", "theme-dark", "theme-high-contrast"];
const THEME_SUBGROUPS = ["surface", "text", "border", "state"];

// Collect leaf token paths under `obj` as dot-separated names.
function leaves(obj, prefix = []) {
    const out = [];
    for (const [k, v] of Object.entries(obj || {})) {
        if (k.startsWith("$")) continue;
        if (v && typeof v === "object" && "$value" in v) {
            out.push([...prefix, k].join("."));
        } else if (v && typeof v === "object") {
            out.push(...leaves(v, [...prefix, k]));
        }
    }
    return out;
}

test("DTCG: file is multi-set Tokens-Studio shape", () => {
    assert.ok(json.global, "missing 'global' set");
    for (const set of THEME_SETS) {
        assert.ok(json[set], `missing theme set: ${set}`);
    }
    assert.ok(Array.isArray(json.$themes), "missing $themes array");
    assert.equal(json.$themes.length, 3, "exactly 3 themes expected");
    assert.deepEqual(
        json.$metadata?.tokenSetOrder,
        ["global", "theme-light", "theme-dark", "theme-high-contrast"],
        "tokenSetOrder must list global first then the three themes",
    );
});

test("DTCG: every theme defines the same surface / text / border / state keys", () => {
    const refKeys = {};
    for (const sub of THEME_SUBGROUPS) {
        refKeys[sub] = leaves(json["theme-light"].color[sub]).sort();
        assert.ok(refKeys[sub].length > 0, `theme-light.color.${sub} is empty`);
    }
    for (const set of ["theme-dark", "theme-high-contrast"]) {
        for (const sub of THEME_SUBGROUPS) {
            const here = leaves(json[set].color[sub]).sort();
            assert.deepEqual(
                here, refKeys[sub],
                `${set}.color.${sub} key set diverges from theme-light`,
            );
        }
    }
});

test("DTCG: every theme defines elevation 0..4", () => {
    for (const set of THEME_SETS) {
        const keys = Object.keys(json[set].elevation || {}).sort();
        assert.deepEqual(keys, ["0", "1", "2", "3", "4"],
            `${set}.elevation must define exactly 0..4`);
    }
});

test("DTCG: global palette tokens (bucket, ext, neutral, brand) have hex values", () => {
    const hexRe = /^#[0-9a-fA-F]{6}$/;
    for (const t of leaves(json.global.color.bucket)) {
        const v = t.split(".").reduce((o, k) => o[k], json.global.color.bucket);
        assert.match(v.$value, hexRe, `bucket.${t} must be a 6-digit hex`);
    }
    for (const n of ["0", "100", "200", "300", "400", "500", "600", "700", "800", "900", "950"]) {
        const v = json.global.color.neutral[n];
        assert.ok(v && v.$value, `neutral.${n} must exist`);
        assert.match(v.$value, hexRe, `neutral.${n} must be a 6-digit hex`);
    }
});

test("SCSS: header marks the file as generated (do-not-edit warning)", () => {
    assert.match(scss, /Generated by `pnpm run tokens`/);
    assert.match(scss, /DO NOT EDIT BY HAND/);
});

test("SCSS: emits :root + per-theme [data-theme] blocks", () => {
    assert.match(scss, /:root,\s*\[data-theme="light"\]\s*{/,
        ":root and [data-theme=\"light\"] should share the same block");
    assert.match(scss, /\[data-theme="dark"\]\s*{/);
    assert.match(scss, /\[data-theme="high-contrast"\]\s*{/);
});

test("SCSS: every theme block defines the same theme-switchable custom properties", () => {
    const THEME_VARS = [
        "--ods-surface-canvas", "--ods-surface-raised", "--ods-surface-sunken", "--ods-surface-overlay",
        "--ods-text-primary", "--ods-text-secondary", "--ods-text-muted", "--ods-text-on-brand", "--ods-text-inverse",
        "--ods-border-subtle", "--ods-border-default", "--ods-border-strong",
        "--ods-state-success-bg", "--ods-state-success-fg",
        "--ods-state-warning-bg", "--ods-state-warning-fg",
        "--ods-state-danger-bg",  "--ods-state-danger-fg",
        "--ods-state-info-bg",    "--ods-state-info-fg",
        "--ods-elevation-0", "--ods-elevation-1", "--ods-elevation-2", "--ods-elevation-3", "--ods-elevation-4",
    ];
    for (const v of THEME_VARS) {
        for (const theme of ["light", "dark", "high-contrast"]) {
            const blockRe = new RegExp(
                `(?:\\[data-theme="${theme}"\\]|:root,\\s*\\[data-theme="light"\\])\\s*{[^}]*${v.replace(/-/g, "\\-")}:`,
                "s",
            );
            assert.match(scss, blockRe,
                `var ${v} missing from [data-theme="${theme}"] block`);
        }
    }
});

test("SCSS: bucket palette + ext map are Sass maps, not CSS custom properties", () => {
    assert.match(scss, /\$ods-bucket-palette:\s*\(/);
    assert.match(scss, /\$ods-extension-accents:\s*\(/);
    // The "image" / "media" anchor keys are intentionally absent from the
    // runtime Sass map (concrete extensions reference them via DTCG aliases).
    const extBlock = scss.match(/\$ods-extension-accents:\s*\(([^)]+)\)/s)?.[1] ?? "";
    for (const anchor of ["image", "media", "doc-family", "sheet", "archive"]) {
        assert.doesNotMatch(extBlock, new RegExp(`^\\s*"${anchor}"\\s*:`, "m"),
            `ext anchor "${anchor}" should not appear in the runtime Sass map`);
    }
});

test("SCSS: legacy aliases that pre-Phase-0 consumers reference are still emitted", () => {
    const legacy = [
        "--ods-card-shadow",
        "--ods-card-shadow-hover",
        "--ods-card-lift-duration",
        "--ods-card-lift-easing",
        "--ods-card-radius",
        "--ods-chip-radius",
        "--ods-tile-size",
        "--ods-avatar-size",
        "--ods-spine-width",
    ];
    for (const v of legacy) {
        assert.match(scss, new RegExp(v.replace(/-/g, "\\-")),
            `legacy alias ${v} must remain emitted for back-compat`);
    }
});
